global:
  scrape_interval: 15s

scrape_configs:
  - job_name: java-api
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["java-api:8080"]

  - job_name: fraud-engine
    metrics_path: /metrics
    static_configs:
      - targets: ["fraud-engine:8000"]
